#!/bin/sh
# Checks that the source tarball holds only files tracked in git, plus the
# files R CMD build generates (inst/doc/ and build/). A file left at the
# package root, such as a CI log, is otherwise packed by R CMD build, which
# reads .Rbuildignore but not .gitignore.
#
# Usage: sh tools/check_tarball.sh [rsimd_<version>.tar.gz]
# Without an argument the package is built with R CMD build in a temporary
# directory and that tarball is checked. Exit status is non-zero when the
# tarball holds an untracked file.

set -eu

LC_ALL=C
export LC_ALL

root=$(cd "$(dirname "$0")/.." && pwd -P)

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT HUP INT TERM

git -C "$root" ls-files > "$tmp/tracked" 2> /dev/null || {
  echo "not a git checkout: $root" >&2
  exit 2
}

if [ $# -ge 1 ]; then
  tarball=$1
else
  echo "Building the source tarball with R CMD build"
  (cd "$tmp" && "${R_HOME:+$R_HOME/bin/}R" CMD build --no-build-vignettes --no-manual \
    "$root" > build.log 2>&1) || {
    cat "$tmp/build.log" >&2
    echo "R CMD build failed" >&2
    exit 1
  }
  tarball=$(ls "$tmp"/*.tar.gz)
fi
[ -f "$tarball" ] || { echo "no such tarball: $tarball" >&2; exit 1; }

tar tzf "$tarball" | grep -v '/$' | sed 's#^[^/]*/##' |
  grep -Ev '^(inst/doc|build)/' | sort > "$tmp/packed"
sort "$tmp/tracked" > "$tmp/tracked.sorted"
untracked=$(comm -23 "$tmp/packed" "$tmp/tracked.sorted")

if [ -n "$untracked" ]; then
  echo "FAIL $(basename "$tarball") holds files not tracked in git:"
  echo "$untracked" | sed 's/^/  /'
  echo "Remove them or add them to .Rbuildignore."
  exit 1
fi
echo "ok   $(basename "$tarball"): $(wc -l < "$tmp/packed" | tr -d ' ') files, all tracked in git (or generated by R CMD build)"
