#!/bin/sh
# Generate the SLEEF inline headers into src/vendor/sleef.
#
# Maintainer tool; it is not run at install time and needs network access
# (unless SLEEF_SRC names a checkout), CMake >= 3.18, sed and C compilers.
#
# SLEEF does not ship its inline headers: they are generated by its CMake
# build (-DSLEEF_BUILD_INLINE_HEADERS=TRUE). This script fetches SLEEF at the
# pinned tag, runs that build for the x86-64 headers (sse2, avx2, avx512f)
# and the aarch64 headers (advsimd, sve), and copies them into
# src/vendor/sleef after these changes, which make them double precision
# only, independent of the generating machine and quiet under -Wall:
#
#   - single precision is left out: the preprocessed sleefsimdsp.c part of
#     each header is emptied before the final steps of SLEEF's pipeline, so
#     no float function is emitted (the double and float parts are
#     generated separately and concatenated, so nothing double depends on
#     the float part);
#   - SLEEF_FLOAT128_IS_IEEEQP and SLEEF_LONGDOUBLE_IS_IEEEQP, which SLEEF
#     sets from a C++ compile test on the generating machine and which only
#     affect the unused quad-precision type, are left undefined;
#   - `#pragma STDC FP_CONTRACT OFF`, which GCC ignores with a warning, is
#     removed: every file that includes a header is compiled with
#     -ffp-contract=off instead;
#   - the few helpers declared plain `static` are made `static inline`, so
#     unused ones do not warn;
#   - the advsimd and sve headers get back the ARM Ltd. copyright notice of
#     the helper headers they are generated from.
#
# Each architecture's headers are generated natively when the machine has
# that architecture and with a cross compiler otherwise (CMake toolchain
# file plus SLEEF's NATIVE_BUILD_DIR for the host tools). Both routes give
# byte-identical headers; the GitHub Actions workflow vendor-sleef.yml
# (manual trigger) runs this script on x86-64 and arm64 machines and checks
# the result against the vendored files.
#
# Usage: sh tools/vendor_sleef.sh [--arch x86_64|aarch64|all] [--out DIR]
#   --arch  headers to generate (default all)
#   --out   output directory (default src/vendor/sleef). Only a run with
#           --arch all into src/vendor/sleef also rewrites VERSION, LICENSE.txt
#           and the SLEEF section of inst/COPYRIGHTS.
# Environment:
#   CC, CXX           host C and C++ compilers (default cc and c++; SLEEF's
#                     CMake wants them from the same compiler release)
#   CROSS_CC_X86_64   cross compilers used when the machine has the other
#   CROSS_CC_AARCH64  architecture (defaults x86_64-linux-gnu-gcc and
#                     aarch64-linux-gnu-gcc; the C++ compiler is the same
#                     name with g++ for gcc, else the host one)
#   CMAKE             cmake program (default cmake)
#   SLEEF_SRC         an existing SLEEF checkout at SLEEF_COMMIT to use
#                     instead of cloning
#   JOBS              parallel build jobs (default 4)
#   SLEEF_FORCE_CROSS=1  use the cross route for every architecture, even
#                     this machine's (to check that both routes agree)
#
# The SVE header needs a compiler with SVE support (GCC >= 8 or clang on
# Linux); Apple's clang cannot generate it, so run the aarch64 part on Linux.
#
# To update SLEEF, change SLEEF_TAG and SLEEF_COMMIT deliberately, re-run
# this script, then rebuild the package and run tools/check_size.sh.

set -eu

SLEEF_REPO=https://github.com/shibatch/sleef
SLEEF_TAG=3.9.0
SLEEF_COMMIT=906ca7512ee483296780a81a21b9ca715d40dfe1
SLEEF_BUDGET_BYTES=2500000

LC_ALL=C
export LC_ALL

root=$(cd "$(dirname "$0")/.." && pwd -P)
dest="$root/src/vendor/sleef"
copyrights="$root/inst/COPYRIGHTS"
cmake=${CMAKE:-cmake}
jobs=${JOBS:-4}

die() {
  echo "vendor_sleef.sh: $*" >&2
  exit 1
}

arches=all
out=$dest
while [ $# -gt 0 ]; do
  case "$1" in
    --arch) [ $# -ge 2 ] || die "--arch needs a value"; arches=$2; shift 2 ;;
    --out) [ $# -ge 2 ] || die "--out needs a value"; out=$2; shift 2 ;;
    -h | --help) sed -n '2,/^$/s/^# \{0,1\}//p' "$0"; exit 0 ;;
    *) die "unknown argument '$1'" ;;
  esac
done
case "$arches" in
  all) arches="x86_64 aarch64" ;;
  x86_64 | aarch64) ;;
  *) die "--arch must be x86_64, aarch64 or all" ;;
esac
mkdir -p "$out"
out=$(cd "$out" && pwd -P)
full_update=no
if [ "$arches" = "x86_64 aarch64" ] && [ "$out" = "$dest" ]; then
  full_update=yes
fi

command -v "$cmake" > /dev/null 2>&1 || die "cmake not found (set CMAKE)"

case "$(uname -m)" in
  x86_64 | amd64) host_arch=x86_64 ;;
  aarch64 | arm64) host_arch=aarch64 ;;
  *) host_arch=other ;;
esac

# SLEEF's ISA names per architecture, and our file names.
sleef_isas() {
  case "$1" in
    x86_64) echo "SSE2 AVX2 AVX512F" ;;
    aarch64) echo "ADVSIMD SVE" ;;
  esac
}

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT HUP INT TERM

if [ -n "${SLEEF_SRC:-}" ]; then
  src=$(cd "$SLEEF_SRC" && pwd -P)
  echo "Using the SLEEF checkout in $src"
else
  echo "Fetching SLEEF $SLEEF_TAG"
  src="$tmp/sleef"
  git clone -q --depth 1 --branch "$SLEEF_TAG" "$SLEEF_REPO" "$src" 2> /dev/null ||
    die "could not clone $SLEEF_REPO at $SLEEF_TAG"
fi
[ "$(git -C "$src" rev-parse HEAD)" = "$SLEEF_COMMIT" ] ||
  die "the SLEEF checkout is not at $SLEEF_COMMIT ($SLEEF_TAG)"
commit_date=$(git -C "$src" log -1 --format=%cs)

sleef_options="-DSLEEF_BUILD_INLINE_HEADERS=TRUE -DSLEEF_BUILD_LIBM=OFF -DSLEEF_BUILD_DFT=OFF
  -DSLEEF_BUILD_QUAD=OFF -DSLEEF_BUILD_TESTS=OFF -DSLEEF_BUILD_SCALAR_LIB=OFF
  -DSLEEF_BUILD_GNUABI_LIBS=OFF -DSLEEF_ENABLE_LTO=OFF -DCMAKE_BUILD_TYPE=Release"

# configure_build <build dir> <log> [extra cmake arguments ...]
configure_build() {
  b=$1
  log=$2
  shift 2
  # shellcheck disable=SC2086 # sleef_options is a word list
  "$cmake" -S "$src" -B "$b" $sleef_options "$@" > "$log" 2>&1 ||
    { cat "$log" >&2; die "cmake configure failed in $b"; }
}

build_headers() {
  "$cmake" --build "$1" --target inline_headers_util -j "$jobs" >> "$2" 2>&1 ||
    { tail -40 "$2" >&2; die "generating the inline headers failed in $1"; }
}

# Host build: native headers for this machine's architecture and the host
# tools (addSuffix, mkrename ...) that a cross build runs.
host_build="$tmp/build-host"
host_cc=${CC:-cc}
host_cxx=${CXX:-c++}
echo "Configuring the host build ($host_arch, $host_cc)"
configure_build "$host_build" "$tmp/host.log" \
  -DCMAKE_C_COMPILER="$host_cc" -DCMAKE_CXX_COMPILER="$host_cxx"
build_headers "$host_build" "$tmp/host.log"
compilers=""

for arch in $arches; do
  if [ "$arch" = "$host_arch" ] && [ "${SLEEF_FORCE_CROSS:-0}" != 1 ]; then
    b=$host_build
    cc_used=$host_cc
  else
    case "$arch" in
      x86_64) cross=${CROSS_CC_X86_64:-x86_64-linux-gnu-gcc} ;;
      aarch64) cross=${CROSS_CC_AARCH64:-aarch64-linux-gnu-gcc} ;;
    esac
    command -v "$cross" > /dev/null 2>&1 ||
      die "cross compiler '$cross' for $arch not found (set CROSS_CC_$(echo "$arch" | tr a-z A-Z))"
    case "$cross" in
      *gcc) cross_cxx="${cross%gcc}g++" ;;
      *clang) cross_cxx="${cross}++" ;;
      *) cross_cxx=$cross ;;
    esac
    # SLEEF only uses C++ for configure tests whose results are normalised
    # below, so the host C++ compiler will do when there is no cross one.
    command -v "$cross_cxx" > /dev/null 2>&1 || cross_cxx=$host_cxx
    b="$tmp/build-$arch"
    cat > "$tmp/toolchain-$arch.cmake" << EOF
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR $arch)
set(CMAKE_C_COMPILER $cross)
set(CMAKE_CXX_COMPILER $cross_cxx)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
EOF
    echo "Configuring the cross build for $arch ($cross)"
    configure_build "$b" "$tmp/$arch.log" \
      -DCMAKE_TOOLCHAIN_FILE="$tmp/toolchain-$arch.cmake" -DNATIVE_BUILD_DIR="$host_build"
    build_headers "$b" "$tmp/$arch.log"
    cc_used=$cross
  fi
  compilers="$compilers
  $arch: $("$cc_used" --version 2> /dev/null | head -n 1) (via $cc_used)"

  # Empty the single-precision part and regenerate everything after it.
  for isa in $(sleef_isas "$arch"); do
    lc=$(echo "$isa" | tr A-Z a-z)
    sp="$b/src/libm/sleefsimdsp$isa.h.tmp"
    [ -f "$sp" ] || die "$sp not found: SLEEF's generation pipeline has changed"
    : > "$sp"
    rm -f "$b/src/libm/sleef$isa.h.c" "$b/src/libm/sleef$isa.h.tmp3" \
      "$b/src/libm/sleef$isa.h.tmp4" "$b/src/libm/sleef$isa.h.tmp5" \
      "$b/include/sleefinline_$lc.h"
  done
  build_headers "$b" "$tmp/$arch.log"

  for isa in $(sleef_isas "$arch"); do
    lc=$(echo "$isa" | tr A-Z a-z)
    h="$b/include/sleefinline_$lc.h"
    [ -s "$h" ] || die "$h was not generated (does $cc_used support $isa?)"
    if grep -q '^SLEEF_INLINE.* Sleef_[a-z0-9]*f[0-9x]*_' "$h"; then
      die "sleefinline_$lc.h still contains single-precision functions"
    fi
    grep -q '^#pragma STDC FP_CONTRACT OFF$' "$h" || die "sleefinline_$lc.h: FP_CONTRACT pragma not found"
    # SLEEF's generator drops the ARM copyright notice of the helper
    # headers the AdvSIMD and SVE code comes from; keep it.
    case "$lc" in
      advsimd | sve) arm_notice='\
//   Copyright ARM Ltd. 2010 - 2024.' ;;
      *) arm_notice= ;;
    esac
    sed -e "1s|^\(//   Copyright Naoki Shibata and contributors .*\)$|\1$arm_notice|" \
      -e "s|^\(// This file is generated by SLEEF .*\)$|\1\\
// and was then edited by rsimd's tools/vendor_sleef.sh: single precision\\
// removed, host-dependent quad-precision settings cleared, FP_CONTRACT\\
// pragma removed (compile with -ffp-contract=off) and plain static\\
// helpers made inline.|" \
      -e 's|^#define SLEEF_FLOAT128_IS_IEEEQP$|/* #undef SLEEF_FLOAT128_IS_IEEEQP */|' \
      -e 's|^#define SLEEF_LONGDOUBLE_IS_IEEEQP$|/* #undef SLEEF_LONGDOUBLE_IS_IEEEQP */|' \
      -e 's|^#pragma STDC FP_CONTRACT OFF$|/* -ffp-contract=off is required */|' \
      -e 's/^static \(SLEEF_CONST \)\{0,1\}\([A-Za-z_][A-Za-z0-9_]* [A-Za-z_][A-Za-z0-9_]*(\)/static inline \1\2/' \
      "$h" > "$out/sleefinline_$lc.h"
    chmod 644 "$out/sleefinline_$lc.h"
    echo "  sleefinline_$lc.h: $(wc -c < "$out/sleefinline_$lc.h" | tr -d ' ') bytes"
  done
done

[ "$full_update" = yes ] || {
  echo "Generated the $arches headers into $out"
  exit 0
}

nbytes=$(cat "$dest"/sleefinline_*.h | wc -c | tr -d ' ')
echo "SLEEF headers: $nbytes bytes (budget $SLEEF_BUDGET_BYTES)"
[ "$nbytes" -le "$SLEEF_BUDGET_BYTES" ] || die "the SLEEF headers exceed their size budget"

cp "$src/LICENSE.txt" "$dest/LICENSE.txt"
chmod 644 "$dest/LICENSE.txt"
cat > "$dest/VERSION" << EOF
SLEEF inline headers generated by tools/vendor_sleef.sh
repository: $SLEEF_REPO
tag: $SLEEF_TAG
commit: $SLEEF_COMMIT
commit date: $commit_date
generated: $(date -u +%Y-%m-%d)
compilers:$compilers
headers: $(cd "$dest" && ls sleefinline_*.h | tr '\n' ' ' | sed 's/ $//')
header bytes: $nbytes
EOF
chmod 644 "$dest/VERSION"

# Refresh the SLEEF section of inst/COPYRIGHTS.
section="$tmp/section.txt"
{
  echo "-- BEGIN SLEEF (generated by tools/vendor_sleef.sh) --"
  echo
  echo "SLEEF (SIMD Library for Evaluating Elementary Functions)"
  echo "--------------------------------------------------------"
  echo
  echo "Files:   src/vendor/sleef (headers generated from SLEEF, in the source"
  echo "         package only; see src/vendor/sleef/VERSION)"
  echo "Source:  $SLEEF_REPO"
  echo "Tag:     $SLEEF_TAG ($SLEEF_COMMIT, $commit_date)"
  echo "Licence: Boost Software License 1.0"
  echo
  echo "Copyright Naoki Shibata and contributors 2010 - 2025."
  echo "The AdvSIMD and SVE code is also Copyright ARM Ltd. 2010 - 2024."
  echo
  echo "SLEEF licence text (src/vendor/sleef/LICENSE.txt):"
  echo
  sed -e 's/^/  /' -e 's/[ \t]*$//' "$src/LICENSE.txt"
  echo
  echo "-- END SLEEF --"
} > "$section"

awk -v section="$section" '
  function emit(   line) {
    while ((getline line < section) > 0) print line
    close(section)
    done = 1
  }
  /^-- BEGIN SLEEF / { skip = 1; emit(); next }
  /^-- END SLEEF --$/ { skip = 0; next }
  skip { next }
  { print }
  END { if (!done) { print ""; emit() } }
' "$copyrights" | awk 'NF { blank = 0; print; next } !blank++' > "$tmp/COPYRIGHTS"
cp "$tmp/COPYRIGHTS" "$copyrights"

echo "Vendored SLEEF $SLEEF_TAG ($SLEEF_COMMIT) into src/vendor/sleef"
